# Ref: https://github.com/percona/percona-xtradb-cluster-operator/blob/v1.13.0/deploy/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aliyun-pxc.clusterName" . }}-secrets
type: Opaque
stringData:
  root: {{ include "aliyun-pxc.userRoot" . }}
  xtrabackup: {{ include "aliyun-pxc.userXtrabackup" . }}
  monitor: {{ include "aliyun-pxc.userMonitor" . }}
  clustercheck: {{ include "aliyun-pxc.userClustercheck" . }}
  proxyadmin: {{ include "aliyun-pxc.userProxyadmin" . }}
  #  pmmserverkey: my_pmm_server_key
  operator: {{ include "aliyun-pxc.userOperator" . }}
  replication: {{ include "aliyun-pxc.userReplication" . }}