# Ref: https://github.com/percona/percona-xtradb-cluster-operator/blob/v1.13.0/deploy/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cluster1-secrets
type: Opaque
stringData:
  root: root_password
  xtrabackup: backup_password
  monitor: monitory
  clustercheck: clustercheckpassword
  proxyadmin: admin_password
  #  pmmserverkey: my_pmm_server_key
  operator: operatoradmin
  replication: repl_password